sudo: required

language: c

install:
  - sudo pip install hererocks
  - hererocks lua --lua 5.1 -r latest
  - source lua/bin/activate
  - luarocks install luacheck

  - wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
  - sudo apt-get update
  - sudo apt-get install openresty cpanminus

  - sudo cpanm -q -n Test::Nginx

script:
- make check
- make test
